### ISSUE TITLE
latest commit is failing

### ISSUE THREAD

**Issue by amitu** [xkrishguptaa/workshop-fastn#3]
@xkrishguptaa the latest commit is failing, people are using this repo for conducting workshop, lets fix the issue so they have a better experience. Let me know if you need help with this.

**Comment by kkrishguptaa** [comment]
Hi, Amit, I am not sure what you are talking about the last commit at the time of the issue opening was 65b0a13d881285070a859415702632daaee53154 and all the checks passed on it!

However I still ran the code manually, it was running perfectly!

I did push some changes to the repo right now though, hopefully you seem to like that more :)
